name: IRC notifications

on: [push, pull_request, create, issues]

jobs:
  notification:
    runs-on: ubuntu-22.04
    name: IRC Notification
    steps:
    - name: Commit
      uses: Gottox/irc-message-action@v2
      if: github.event_name == 'push'
      with:
        channel: '#aircrack-ng'
        nickname: github-aircrack-ng
        message: |-
          Commit by ${{ github.actor }}: ${{ github.event.compare }}
          ${{ join(github.event.commits.*.message) }}

    - name: Pull Request Created
      uses: Gottox/irc-message-action@v2
      if: github.event_name == 'pull_request'
      with:
        channel: '#aircrack-ng'
        nickname: github-aircrack-ng
        message: |-
          New pull request by ${{ github.actor }}: ${{ github.event.pull_request.title }} - ${{ github.event.pull_request.html_url }}

    - name: Issue created
      uses: Gottox/irc-message-action@v2
      if: github.event_name == 'issues' && github.event.action == 'opened' && github.event.issue.draft == false
      with:
        channel: '#aircrack-ng'
        nickname: github-aircrack-ng
        message: |-
          New issue #${{github.event.issue.number}} (${{github.event.issue.url}}) by ${{ github.actor }}: ${{github.event.issue.title}} ()

    - name: New tag/release
      uses: Gottox/irc-message-action@v2
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      with:
        channel: '#aircrack-ng'
        nickname: github-aircrack-ng
        message: |-
          New release in GitHub: ${{ github.event.ref }}