name: Other Linux testing

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/manual.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/manual.yml'
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "* * 2 * *"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v3
      - 
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile
          verbose: true
          failure-threshold: error
      - 
        name: Lint Release Dockerfile
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: './Dockerfile.release'
          verbose: true
          failure-threshold: error
      -
        name: Shellcheck package install script
        uses: sudo-bot/action-shellcheck@latest
        with:
          cli-args: "docker_package_install.sh"

  linux:
    runs-on: ubuntu-22.04
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        platform: [ 'clearlinux:base', 'rockylinux:9', 'almalinux:9', 'opensuse/leap:15', 'archlinux:base' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push on linux/amd64
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          build-args: "IMAGE_BASE=${{ matrix.platform }}"
          push: false